### ISSUE TITLE
Suggestion: Remove node type definitions from Neos.NodeTypes

### ISSUE THREAD

**Issue by jonnitto** [medienreaktor/Medienreaktor.Meilisearch#4]
In many installations, `Neos.NodeTypes` is not installed. I would suggest removing those [definitions](https://github.com/medienreaktor/Medienreaktor.Meilisearch/blob/main/Configuration/NodeTypes.yaml#L54-L70) and add a section with examples in the readme file

**Comment by danielkestler** [comment]
Probably a leftover from the Elasticsearch-implementation. Thank you, will remove it.
