### ISSUE TITLE
Some properties are indexed twice

### ISSUE THREAD

**Issue by jonnitto** [medienreaktor/Medienreaktor.Meilisearch#6]
Following properties are indexed twice, is this on purpose?

* `_nodeType` and `__nodeType`
* `_path` and `__path `

**Comment by danielkestler** [comment]
One may argue about that, but it is indeed on purpose, see README:

> You will see that some properties are indexed twice, like _path and __path, _nodeType and __nodeType. This is due to the different privacy of these node properties:
> 
> + _*-properties are default Neos node properties that are private to Neos (and may change)
> + __*-properties are private properties that are required for the Meilisearch-integration
>
> We have to make sure that our required properties are always there, so we better index them separately.
